### ISSUE TITLE
No delete option to skills

### ISSUE THREAD

**Issue by vamsikrishnareddybevara** [ManojSatishkumar/msk-components#58]
![image](https://user-images.githubusercontent.com/38369869/88684449-80476300-d112-11ea-90b6-15bbf06cafc3.png)
We can provide a delete icon for each skill(delete icon ...right side to each text field)

**Comment by Rajdp07** [comment]
yes why not? are you working on it?

**Comment by vamsikrishnareddybevara** [comment]
yes, I'm working on it.

**Comment by ManojSatishkumar** [comment]
This project is not msk-components

**Comment by ManojSatishkumar** [comment]
This project is not msk-components
