### ISSUE TITLE
breaking bug because of localStorage cache

### ISSUE THREAD

**Issue by AKAspanion** [ManojSatishkumar/msk-components#7]
If I create a component/variant and then revert it back. 
It causes the whole application to crashes, I need to clear my localStorage in order to fix it.

![image](https://user-images.githubusercontent.com/25038931/88484710-359cde00-cf8e-11ea-9ea9-2b3885600a25.png)

Reason: selectedVariant key returned from localStorage is no longer present in the application.

![image](https://user-images.githubusercontent.com/25038931/88484735-71d03e80-cf8e-11ea-99b7-850f493450e6.png)

**Comment by AKAspanion** [comment]
@ManojSatishkumar

**Comment by ManojSatishkumar** [comment]
@AKAspanion :  Why don't you engineer a fix for this and send PR

**Comment by AKAspanion** [comment]
@ManojSatishkumar sure
